name: 00 - Custom Binutils Build RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ['almalinux:9', 'almalinux:8']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Sysbox
      run: |
        curl -LO https://downloads.nestybox.com/sysbox/releases/v0.6.4/sysbox-ce_0.6.4-0.linux_amd64.deb
        sudo dpkg -i sysbox-ce_0.6.4-0.linux_amd64.deb || sudo apt-get install -f

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up AlmaLinux container and build custom binutils using rpmbuild
      run: |
        mkdir -p ${{ github.workspace }}/rpms
        docker pull ${{ matrix.os }}
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ${{ matrix.os }} /bin/bash -c "
          if [[ '${{ matrix.os }}' == 'almalinux:8' ]]; then
            DISTTAG='el8'
          else
            DISTTAG='el9'
          fi

          # Copy the build script and run it
          cp /workspace/build-binutils-custom.sh /tmp
          chmod +x /tmp/build-binutils-custom.sh
          /tmp/build-binutils-custom.sh \$DISTTAG

          # Copy the built RPMs to the mounted /workspace/rpms directory on the host
          mkdir -p /workspace/rpms
          cp /root/rpmbuild/RPMS/x86_64/*.rpm /workspace/rpms/
          cp /root/rpmbuild/SRPMS/*.rpm /workspace/rpms/

          # List the RPMs in the /workspace/rpms directory
          echo
          ls -lah /workspace/rpms/

          # Install the built RPM (non-debug version)
          echo
          yum localinstall -y /root/rpmbuild/RPMS/x86_64/binutils-custom-*.x86_64.rpm

          # Check package files
          echo
          rpm -ql binutils-custom | tee /workspace/binutils-qpl-output.log

          # Changelog check
          echo
          rpm -q --changelog binutils-custom | tee /workspace/binutils-changelog-output.log

          # Check the installed RPM details
          echo
          yum -q info binutils-custom | tee /workspace/binutils-yuminfo-output.log

          # Check the binutils version
          echo
          source /etc/profile.d/binutils-custom.sh
          ld --version | tee /workspace/binutils-version-output.log
          echo | tee -a /workspace/binutils-version-output.log
          ${PREFIX}/bin/ld --version | tee -a /workspace/binutils-version-output.log
        "

    - name: Display binutils version
      run: |
        echo "Displaying binutils version:"
        cat ${{ github.workspace }}/binutils-version-output.log

    - name: Display binutils qpl info
      run: |
        echo "Displaying binutils qpl info:"
        cat ${{ github.workspace }}/binutils-qpl-output.log

    - name: Display binutils changelog info
      run: |
        echo "Displaying binutils changelog info:"
        cat ${{ github.workspace }}/binutils-changelog-output.log

    - name: Display binutils yum info
      run: |
        echo "Displaying binutils yum info:"
        cat ${{ github.workspace }}/binutils-yuminfo-output.log

    - name: Debugging Show contents of /workspace/rpms
      run: |
        echo "Checking for RPMs in /workspace/rpms on host..."
        ls -lah ${{ github.workspace }}/rpms/

    - name: Set custom artifact name
      run: |
        if [[ ${{ matrix.os }} == 'almalinux:8' ]]; then
          echo "ARTIFACT_NAME=binutils-custom-rpms-almalinux-8" >> $GITHUB_ENV
        else
          echo "ARTIFACT_NAME=binutils-custom-rpms-almalinux-9" >> $GITHUB_ENV
        fi

    - name: Upload RPM
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ github.workspace }}/rpms/*.rpm
        if-no-files-found: warn
        retention-days: 7
